# Generated by Django 3.1 on 2020-09-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media_type', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
